from __future__ import annotations

import math
import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
(ROOT / ".cache" / "matplotlib").mkdir(parents=True, exist_ok=True)
os.environ.setdefault("XDG_CACHE_HOME", str(ROOT / ".cache"))
os.environ.setdefault("MPLCONFIGDIR", str(ROOT / ".cache" / "matplotlib"))
if "--no-show" in sys.argv:
    os.environ.setdefault("MPLBACKEND", "Agg")
sys.path.insert(0, str(ROOT))

import matplotlib.pyplot as plt
import numpy as np

from mr_utils import (
    adjoint,
    exp_twist,
    inv_transform,
    matrix_log6,
    normalize,
    rot_axis_angle,
    se3_to_vec,
    so3_log,
    transform,
    unskew,
)


def plot_frame(ax, T, label, scale=0.25):
    origin = T[:3, 3]
    axes = T[:3, :3]
    colors = ["tab:red", "tab:green", "tab:blue"]
    for i, color in enumerate(colors):
        ax.quiver(*origin, *(scale * axes[:, i]), color=color, linewidth=2)
    ax.text(*origin, label)


def set_equal_3d(ax):
    limits = np.array([ax.get_xlim3d(), ax.get_ylim3d(), ax.get_zlim3d()])
    center = limits.mean(axis=1)
    radius = 0.5 * np.max(limits[:, 1] - limits[:, 0])
    ax.set_xlim3d(center[0] - radius, center[0] + radius)
    ax.set_ylim3d(center[1] - radius, center[1] + radius)
    ax.set_zlim3d(center[2] - radius, center[2] + radius)


def main(show=True):
    axis = normalize(np.array([0.45, 1.0, 0.25]))
    theta = math.radians(115.0)
    R = rot_axis_angle(axis, theta)

    recovered = unskew(so3_log(R))
    recovered_theta = np.linalg.norm(recovered)
    recovered_axis = recovered / recovered_theta

    q_on_axis = np.array([0.35, -0.15, 0.1])
    pitch = 0.18
    v = -np.cross(axis, q_on_axis) + pitch * axis
    screw_axis = np.r_[axis, v]
    T = exp_twist(screw_axis, theta)

    log_vec = se3_to_vec(matrix_log6(T))

    V_body = np.array([0.3, -0.1, 0.6, 0.2, 0.0, 0.1])
    F_body = np.array([0.4, -0.2, 0.1, 3.0, -1.0, 0.5])
    V_space = adjoint(T) @ V_body
    F_space = np.linalg.inv(adjoint(T)).T @ F_body

    print("SO(3) axis-angle check")
    print(f"  input axis       = {axis.round(4)}")
    print(f"  recovered axis   = {recovered_axis.round(4)}")
    print(f"  recovered theta  = {math.degrees(recovered_theta):.3f} deg")
    print("SE(3) log coordinates [omega*theta, v*theta]")
    print(f"  {log_vec.round(4)}")
    print("Wrench/twist power invariance")
    print(f"  body power  = {float(V_body @ F_body):.6f}")
    print(f"  space power = {float(V_space @ F_space):.6f}")

    point = np.array([0.6, 0.2, 0.1])
    rotated = R @ point
    times = np.linspace(0.0, theta, 90)
    origin_path = np.array([exp_twist(screw_axis, t)[:3, 3] for t in times])
    axis_line = np.array([q_on_axis - 0.7 * axis, q_on_axis + 0.7 * axis])

    fig = plt.figure(figsize=(12, 5))
    ax1 = fig.add_subplot(1, 2, 1, projection="3d")
    plot_frame(ax1, np.eye(4), "{s}")
    plot_frame(ax1, transform(R, np.zeros(3)), "R{s}")
    ax1.quiver(0, 0, 0, *point, color="0.3", label="p")
    ax1.quiver(0, 0, 0, *rotated, color="tab:purple", label="Rp")
    ax1.set_title("SO(3): rotation matrix and exponential coordinates")
    ax1.set_xlabel("x")
    ax1.set_ylabel("y")
    ax1.set_zlabel("z")
    ax1.legend(loc="upper left")
    set_equal_3d(ax1)

    ax2 = fig.add_subplot(1, 2, 2, projection="3d")
    plot_frame(ax2, np.eye(4), "{s}")
    plot_frame(ax2, T, "{b}")
    ax2.plot(origin_path[:, 0], origin_path[:, 1], origin_path[:, 2], "k", label="screw path")
    ax2.plot(axis_line[:, 0], axis_line[:, 1], axis_line[:, 2], "--", color="tab:orange", label="screw axis")
    ax2.scatter(*q_on_axis, color="tab:orange")
    ax2.set_title("SE(3): rigid transform generated by a screw axis")
    ax2.set_xlabel("x")
    ax2.set_ylabel("y")
    ax2.set_zlabel("z")
    ax2.legend(loc="upper left")
    set_equal_3d(ax2)

    fig.tight_layout()
    output_dir = ROOT / "outputs"
    output_dir.mkdir(exist_ok=True)
    output_path = output_dir / "ch03_rigid_body_motions.png"
    fig.savefig(output_path, dpi=160)
    print(f"Saved figure: {output_path}")
    if show:
        plt.show()
    plt.close(fig)


if __name__ == "__main__":
    main(show="--no-show" not in sys.argv)
